apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init
data:
  init.sh: |
    #!/bin/bash
    aws --endpoint-url=http://localhost:4566 s3 mb s3://images-bucket
    aws --endpoint-url=http://localhost:4566 s3api put-bucket-policy \
      --bucket images-bucket \
      --policy '{
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::images-bucket/*"
          }
        ]
      }'